# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Synergy-10-3-3Build

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.x'
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(HarmonyCoreSln)'
- task: MSBuild@1
  inputs:
    solution: '$(HarmonyCoreSln)'
    msbuildArchitecture: 'x64'
    platform: 'x64'
    configuration: 'Release'
    restoreNugetPackages: true